"""Generate the dynamic chunk of dnsmasq config from `managed_devices`
in SQLite, and SIGHUP the dnsmasq container so it re-reads.

The base dnsmasq.conf includes /dhcp-state/managed.conf via `conf-file=`.
We own the contents of that file; the base file is read-only.
"""
from pathlib import Path
import docker

import db
import docker_ctl

MANAGED_CONF = Path("/dhcp-state/managed.conf")
ZTP_SERVER = "http://172.30.0.20"


def render_managed_conf() -> str:
    devices = db.list_managed_devices()
    lines = [
        "# Generated by ztp-app from the managed_devices table. Do not edit.",
        "# Each entry below was registered via POST /api/managed-devices.",
        "",
    ]
    for d in devices:
        tag = d["name"]
        lines.append(f"dhcp-host={d['mac']},{d['mgmt_ip']},set:{tag}")
        lines.append(f"dhcp-boot=tag:{tag},{ZTP_SERVER}/ztp/{tag}.sh")
        lines.append("")
    return "\n".join(lines) + "\n"


def write_managed_conf() -> None:
    MANAGED_CONF.parent.mkdir(parents=True, exist_ok=True)
    MANAGED_CONF.write_text(render_managed_conf())


def reload_dnsmasq() -> None:
    """Restart the dnsmasq container so it re-reads dnsmasq.conf and
    every `conf-file=` it includes. SIGHUP would NOT work here — per the
    dnsmasq man page it only re-reads /etc/hosts, the lease database,
    `dhcp-hostsfile=`, and `dhcp-optsfile=`, but explicitly NOT the main
    config file or its includes (which is where our `dhcp-host` /
    `dhcp-boot` lines live). The dnsmasq container has only eth0, so a
    restart is safe (no fabric veths to lose). Existing leases survive
    via the persisted lease file under /dhcp-state/.
    """
    cli = docker.from_env()
    name = f"clab-{docker_ctl.LAB_NAME}-ztp-dhcp"
    try:
        c = cli.containers.get(name)
    except docker.errors.NotFound:
        return
    c.restart(timeout=5)


def regenerate() -> None:
    """Write the managed-devices file and reload dnsmasq. Safe to call
    on app startup (writes empty file if no devices).
    """
    write_managed_conf()
    try:
        reload_dnsmasq()
    except Exception:
        # dnsmasq not running yet at app startup is fine.
        pass
